// src/pages/FormView.vue
<template>
  <div class="space-y-6">
    <!-- Breadcrumb -->
    <div class="flex items-center space-x-4">
      <Button
        variant="ghost"
        size="sm"
        @click="$router.go(-1)"
      >
        <ArrowLeftIcon class="h-4 w-4 mr-1" />
        Back
      </Button>
      
      <nav class="flex items-center space-x-2 text-sm text-gray-500">
        <span>{{ module }}</span>
        <span>/</span>
        <span>{{ doctype }}</span>
        <template v-if="docname">
          <span>/</span>
          <span class="font-medium">{{ docname }}</span>
        </template>
      </nav>
    </div>

    <!-- Dynamic Form -->
    <DynamicForm
      v-if="doctype"
      :doctype="doctype"
      :docname="docname"
      :mode="mode"
      @save="handleSave"
      @cancel="handleCancel"
    />
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { ArrowLeftIcon } from 'lucide-vue-next'
import { Button } from 'frappe-ui'
import DynamicForm from '@/components/forms/DynamicForm.vue'

interface Props {
  module: string
  doctype: string
  docname?: string
  mode: 'create' | 'edit' | 'view'
}

const props = defineProps<Props>()
const router = useRouter()

const handleSave = (doc: any) => {
  console.log('Document saved:', doc)
  router.push(`/${props.module}/${props.doctype}`)
}

const handleCancel = () => {
  router.go(-1)
}
</script>

// src/pages/FormView.tsx
import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import DynamicForm from '../components/forms/DynamicForm';
import { ArrowLeft } from 'lucide-react';
import Button from '../components/ui/Button';

interface FormViewProps {
  mode: 'create' | 'edit' | 'view';
}

const FormView: React.FC<FormViewProps> = ({ mode }) => {
  const { module, doctype, docname } = useParams();
  const navigate = useNavigate();

  const handleSave = (doc: any) => {
    console.log('Document saved:', doc);
    // Navigate back to list or show success message
    navigate(`/${module}/${doctype}`);
  };

  const handleCancel = () => {
    navigate(-1);
  };

  return (
    <div className="space-y-6">
      {/* Breadcrumb */}
      <div className="flex items-center space-x-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate(-1)}
          icon={<ArrowLeft className="h-4 w-4" />}
        >
          Back
        </Button>
        
        <nav className="flex items-center space-x-2 text-sm text-gray-500">
          <span>{module}</span>
          <span>/</span>
          <span>{doctype}</span>
          {docname && (
            <>
              <span>/</span>
              <span className="font-medium">{docname}</span>
            </>
          )}
        </nav>
      </div>

      {/* Dynamic Form */}
      {doctype && (
        <DynamicForm
          doctype={doctype}
          docname={docname}
          mode={mode}
          onSave={handleSave}
          onCancel={handleCancel}
        />
      )}
    </div>
  );
};

export default FormView;
