// src/components/forms/DynamicForm.vue
<template>
  <div class="space-y-6">
    <!-- Loading State -->
    <div v-if="loading" class="space-y-6">
      <Card class="animate-pulse">
        <div class="h-6 bg-gray-200 dark:bg-gray-700 rounded w-1/4 mb-4"></div>
        <div class="space-y-3">
          <div v-for="i in 4" :key="i" class="h-10 bg-gray-200 dark:bg-gray-700 rounded"></div>
        </div>
      </Card>
    </div>

    <!-- Error State -->
    <ErrorMessage v-else-if="!doctypeData" message="Failed to load form metadata" />

    <!-- Form -->
    <form v-else @submit.prevent="handleSubmit" class="space-y-6">
      <!-- Form Header -->
      <Card>
        <template #header>
          <div class="flex items-center justify-between w-full">
            <div>
              <h2 class="text-lg font-semibold">
                {{ mode === 'create' ? `New ${doctypeData.label}` : currentDoc?.name || doctypeData.label }}
              </h2>
              <div v-if="currentDoc" class="flex items-center space-x-2 mt-1">
                <Badge :variant="getStatusVariant(currentDoc.docstatus)">
                  {{ getStatusLabel(currentDoc.docstatus) }}
                </Badge>
              </div>
            </div>
            
            <div class="flex items-center space-x-2">
              <Button v-if="onCancel" type="button" variant="outline" @click="onCancel" size="sm">
                <XIcon class="h-4 w-4 mr-1" />
                Cancel
              </Button>
              
              <Button
                v-if="!isReadOnly"
                type="submit"
                variant="solid"
                :loading="submitting"
                :disabled="!isDirty && mode === 'edit'"
                size="sm"
              >
                <SaveIcon class="h-4 w-4 mr-1" />
                {{ mode === 'create' ? 'Create' : 'Update' }}
              </Button>
              
              <Button
                v-if="canSubmit"
                type="button"
                variant="solid"
                size="sm"
                @click="handleSubmitDoc"
              >
                <SendIcon class="h-4 w-4 mr-1" />
                Submit
              </Button>
            </div>
          </div>
        </template>
      </Card>

      <!-- Form Sections -->
      <div class="space-y-6">
        <Transition
          v-for="(group, groupIndex) in fieldGroups"
          :key="group.section"
          name="section"
          appear
          :style="{ transitionDelay: `${groupIndex * 100}ms` }"
        >
          <Card>
            <template #header>
              <h3 class="text-base font-medium">{{ group.section }}</h3>
            </template>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div
                v-for="field in group.fields"
                :key="field.fieldname"
                :class="[
                  field.fieldtype === 'Long Text' || field.fieldtype === 'Text Editor' || field.fieldtype === 'HTML Editor' 
                    ? 'md:col-span-2 lg:col-span-3' 
                    : 'col-span-1'
                ]"
              >
                <FieldRenderer
                  :field="field"
                  :value="formData[field.fieldname]"
                  @update:value="formData[field.fieldname] = $event"
                  :error="errors[field.fieldname]"
                  :disabled="isReadOnly || field.read_only"
                  :doctype="doctype"
                  :all-values="formData"
                />
              </div>
            </div>
          </Card>
        </Transition>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { SaveIcon, SendIcon, XIcon } from 'lucide-vue-next'
import { Button, Card, Badge } from 'frappe-ui'
import { useMetadataStore } from '@/stores/metadata'
import { useDocumentStore } from '@/stores/documents'
import type { DocType, DocField, Document } from '@/types/frappe'
import ErrorMessage from '@/components/ui/ErrorMessage.vue'
import FieldRenderer from './FieldRenderer.vue'

interface Props {
  doctype: string
  docname?: string
  mode?: 'create' | 'edit' | 'view'
}

const props = withDefaults(defineProps<Props>(), {
  mode: 'create'
})

const emit = defineEmits<{
  save: [doc: Document]
  cancel: []
}>()

const metadataStore = useMetadataStore()
const documentStore = useDocumentStore()

const loading = ref(false)
const submitting = ref(false)
const doctypeData = ref<DocType | null>(null)
const formData = ref<Record<string, any>>({})
const errors = ref<Record<string, string>>({})
const isDirty = ref(false)

const currentDoc = computed(() => documentStore.currentDoc)
const isReadOnly = computed(() => props.mode === 'view')
const canSubmit = computed(() => 
  doctypeData.value?.is_submittable && currentDoc.value?.docstatus === 0
)

// Group fields by sections
const fieldGroups = computed(() => {
  if (!doctypeData.value) return []

  const groups: { section: string; fields: DocField[] }[] = []
  let currentSection = 'Main'
  let currentFields: DocField[] = []

  doctypeData.value.fields.forEach((field: DocField) => {
    if (field.fieldtype === 'Section Break') {
      if (currentFields.length > 0) {
        groups.push({ section: currentSection, fields: currentFields })
      }
      currentSection = field.label || 'Section'
      currentFields = []
    } else if (field.fieldtype !== 'Column Break' && field.fieldtype !== 'Tab Break') {
      currentFields.push(field)
    }
  })

  if (currentFields.length > 0) {
    groups.push({ section: currentSection, fields: currentFields })
  }

  return groups
})

const loadData = async () => {
  loading.value = true
  try {
    const doctype_data = await metadataStore.loadDocType(props.doctype)
    doctypeData.value = doctype_data
    
    if (props.docname && props.mode !== 'create') {
      await documentStore.loadDocument(props.doctype, props.docname)
    }
    
    initializeFormData()
  } catch (error) {
    console.error('Failed to load form data:', error)
  } finally {
    loading.value = false
  }
}

const initializeFormData = () => {
  const data: Record<string, any> = {}
  
  if (doctypeData.value) {
    doctypeData.value.fields.forEach((field: DocField) => {
      if (field.fieldtype === 'Section Break' || field.fieldtype === 'Column Break' || field.fieldtype === 'Tab Break') {
        return
      }

      if (currentDoc.value && props.mode !== 'create') {
        data[field.fieldname] = currentDoc.value[field.fieldname]
      } else if (field.default !== undefined) {
        data[field.fieldname] = field.default
      } else {
        switch (field.fieldtype) {
          case 'Check':
            data[field.fieldname] = false
            break
          case 'Int':
          case 'Float':
          case 'Currency':
          case 'Percent':
            data[field.fieldname] = 0
            break
          default:
            data[field.fieldname] = ''
        }
      }
    })
  }

  formData.value = data
}

const handleSubmit = async () => {
  if (!doctypeData.value) return

  submitting.value = true
  try {
    const docData: Partial<Document> = {
      doctype: props.doctype,
      ...formData.value,
    }

    if (props.mode !== 'create' && currentDoc.value) {
      docData.name = currentDoc.value.name
    }

    const savedDoc = await documentStore.saveDocument(docData)
    emit('save', savedDoc)
  } catch (error) {
    console.error('Failed to save document:', error)
  } finally {
    submitting.value = false
  }
}

const handleSubmitDoc = async () => {
  if (!currentDoc.value) return
  
  try {
    await documentStore.submitDocument(props.doctype, currentDoc.value.name)
  } catch (error) {
    console.error('Failed to submit document:', error)
  }
}

const getStatusVariant = (docstatus: number) => {
  switch (docstatus) {
    case 0: return 'yellow'
    case 1: return 'green'
    case 2: return 'red'
    default: return 'gray'
  }
}

const getStatusLabel = (docstatus: number) => {
  switch (docstatus) {
    case 0: return 'Draft'
    case 1: return 'Submitted'
    case 2: return 'Cancelled'
    default: return 'Unknown'
  }
}

// Watch for changes to mark form as dirty
watch(formData, () => {
  isDirty.value = true
}, { deep: true })

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.section-enter-active {
  transition: all 0.5s ease-out;
}
.section-enter-from {
  opacity: 0;
  transform: translateY(20px);
}
</style>

// src/components/forms/DynamicForm.tsx
import React, { useEffect, useState, useMemo } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { DocType, DocField, Document, FieldType } from '../../types/frappe';
import { useMetadataStore, useDocumentStore } from '../../store';
import Button from '../ui/Button';
import Input from '../ui/Input';
import Card from '../ui/Card';
import FieldRenderer from './FieldRenderer';
import { motion } from 'framer-motion';
import { Save, Send, X, AlertTriangle } from 'lucide-react';
import { clsx } from 'clsx';

interface DynamicFormProps {
  doctype: string;
  docname?: string;
  onSave?: (doc: Document) => void;
  onCancel?: () => void;
  mode?: 'create' | 'edit' | 'view';
}

const DynamicForm: React.FC<DynamicFormProps> = ({
  doctype,
  docname,
  onSave,
  onCancel,
  mode = 'create',
}) => {
  const { loadDocType, getDocType } = useMetadataStore();
  const { loadDocument, saveDocument, currentDoc } = useDocumentStore();
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [doctypeData, setDoctypeData] = useState<DocType | null>(null);

  // Load DocType and Document
  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      try {
        const doctype_data = await loadDocType(doctype);
        setDoctypeData(doctype_data);
        
        if (docname && mode !== 'create') {
          await loadDocument(doctype, docname);
        }
      } catch (error) {
        console.error('Failed to load form data:', error);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, [doctype, docname, mode, loadDocType, loadDocument]);

  // Generate validation schema
  const validationSchema = useMemo(() => {
    if (!doctypeData) return yup.object();

    const schema: Record<string, any> = {};

    doctypeData.fields.forEach((field: DocField) => {
      if (field.fieldtype === 'Section Break' || field.fieldtype === 'Column Break' || field.fieldtype === 'Tab Break') {
        return;
      }

      let fieldSchema: any;

      switch (field.fieldtype) {
        case 'Int':
        case 'Float':
        case 'Currency':
        case 'Percent':
          fieldSchema = yup.number();
          if (field.validation?.min_value !== undefined) {
            fieldSchema = fieldSchema.min(field.validation.min_value);
          }
          if (field.validation?.max_value !== undefined) {
            fieldSchema = fieldSchema.max(field.validation.max_value);
          }
          break;
        
        case 'Data':
        case 'Small Text':
        case 'Text':
        case 'Long Text':
          fieldSchema = yup.string();
          if (field.validation?.min_length !== undefined) {
            fieldSchema = fieldSchema.min(field.validation.min_length);
          }
          if (field.validation?.max_length !== undefined) {
            fieldSchema = fieldSchema.max(field.validation.max_length);
          }
          if (field.validation?.pattern) {
            fieldSchema = fieldSchema.matches(new RegExp(field.validation.pattern));
          }
          break;
        
        case 'Date':
        case 'Datetime':
          fieldSchema = yup.date();
          break;
        
        case 'Check':
          fieldSchema = yup.boolean();
          break;
        
        case 'Select':
        case 'Link':
          fieldSchema = yup.string();
          break;
        
        default:
          fieldSchema = yup.mixed();
      }

      if (field.reqd && !field.read_only) {
        fieldSchema = fieldSchema.required(`${field.label} is required`);
      }

      schema[field.fieldname] = fieldSchema;
    });

    return yup.object(schema);
  }, [doctypeData]);

  // Initialize form
  const defaultValues = useMemo(() => {
    const values: Record<string, any> = {};
    
    if (doctypeData) {
      doctypeData.fields.forEach((field: DocField) => {
        if (field.fieldtype === 'Section Break' || field.fieldtype === 'Column Break' || field.fieldtype === 'Tab Break') {
          return;
        }

        if (currentDoc && mode !== 'create') {
          values[field.fieldname] = currentDoc[field.fieldname];
        } else if (field.default !== undefined) {
          values[field.fieldname] = field.default;
        } else {
          switch (field.fieldtype) {
            case 'Check':
              values[field.fieldname] = false;
              break;
            case 'Int':
            case 'Float':
            case 'Currency':
            case 'Percent':
              values[field.fieldname] = 0;
              break;
            default:
              values[field.fieldname] = '';
          }
        }
      });
    }

    return values;
  }, [doctypeData, currentDoc, mode]);

  const { control, handleSubmit, watch, formState: { errors, isDirty }, reset } = useForm({
    resolver: yupResolver(validationSchema),
    defaultValues,
    mode: 'onChange',
  });

  // Reset form when data changes
  useEffect(() => {
    reset(defaultValues);
  }, [defaultValues, reset]);

  // Handle form submission
  const onSubmit = async (data: any) => {
    if (!doctypeData) return;

    setSubmitting(true);
    try {
      const docData: Partial<Document> = {
        doctype: doctype,
        ...data,
      };

      if (mode !== 'create' && currentDoc) {
        docData.name = currentDoc.name;
      }

      const savedDoc = await saveDocument(docData);
      onSave?.(savedDoc);
    } catch (error) {
      console.error('Failed to save document:', error);
      // Handle error (show toast notification)
    } finally {
      setSubmitting(false);
    }
  };

  // Group fields by sections
  const fieldGroups = useMemo(() => {
    if (!doctypeData) return [];

    const groups: { section: string; fields: DocField[] }[] = [];
    let currentSection = 'Main';
    let currentFields: DocField[] = [];

    doctypeData.fields.forEach((field: DocField) => {
      if (field.fieldtype === 'Section Break') {
        if (currentFields.length > 0) {
          groups.push({ section: currentSection, fields: currentFields });
        }
        currentSection = field.label || 'Section';
        currentFields = [];
      } else if (field.fieldtype !== 'Column Break' && field.fieldtype !== 'Tab Break') {
        currentFields.push(field);
      }
    });

    if (currentFields.length > 0) {
      groups.push({ section: currentSection, fields: currentFields });
    }

    return groups;
  }, [doctypeData]);

  if (loading) {
    return (
      <Card className="animate-pulse">
        <div className="space-y-4">
          <div className="h-6 bg-gray-200 rounded w-1/4"></div>
          <div className="space-y-3">
            {[1, 2, 3, 4].map(i => (
              <div key={i} className="h-10 bg-gray-200 rounded"></div>
            ))}
          </div>
        </div>
      </Card>
    );
  }

  if (!doctypeData) {
    return (
      <Card>
        <div className="flex items-center space-x-3 text-red-600">
          <AlertTriangle className="h-5 w-5" />
          <span>Failed to load form metadata</span>
        </div>
      </Card>
    );
  }

  const isReadOnly = mode === 'view';
  const canSubmit = doctypeData.is_submittable && currentDoc?.docstatus === 0;

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      {/* Form Header */}
      <Card>
        <Card.Header>
          <div>
            <Card.Title>
              {mode === 'create' ? `New ${doctypeData.label}` : currentDoc?.name || doctypeData.label}
            </Card.Title>
            {currentDoc && (
              <div className="flex items-center space-x-2 mt-1">
                <span className={clsx(
                  'px-2 py-1 rounded-full text-xs font-medium',
                  {
                    'bg-yellow-100 text-yellow-800': currentDoc.docstatus === 0,
                    'bg-green-100 text-green-800': currentDoc.docstatus === 1,
                    'bg-red-100 text-red-800': currentDoc.docstatus === 2,
                  }
                )}>
                  {currentDoc.docstatus === 0 ? 'Draft' : 
                   currentDoc.docstatus === 1 ? 'Submitted' : 'Cancelled'}
                </span>
              </div>
            )}
          </div>
          
          <div className="flex items-center space-x-2">
            {onCancel && (
              <Button type="button" variant="outline" onClick={onCancel} size="sm">
                <X className="h-4 w-4" />
                Cancel
              </Button>
            )}
            
            {!isReadOnly && (
              <Button
                type="submit"
                loading={submitting}
                disabled={!isDirty && mode === 'edit'}
                size="sm"
                icon={<Save className="h-4 w-4" />}
              >
                {mode === 'create' ? 'Create' : 'Update'}
              </Button>
            )}
            
            {canSubmit && (
              <Button
                type="button"
                variant="primary"
                size="sm"
                icon={<Send className="h-4 w-4" />}
              >
                Submit
              </Button>
            )}
          </div>
        </Card.Header>
      </Card>

      {/* Form Sections */}
      <div className="space-y-6">
        {fieldGroups.map((group, groupIndex) => (
          <motion.div
            key={group.section}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: groupIndex * 0.1 }}
          >
            <Card>
              <Card.Header>
                <Card.Title>{group.section}</Card.Title>
              </Card.Header>
              <Card.Content>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {group.fields.map((field: DocField) => (
                    <div
                      key={field.fieldname}
                      className={clsx(
                        field.fieldtype === 'Long Text' || field.fieldtype === 'Text Editor' || field.fieldtype === 'HTML Editor' 
                          ? 'md:col-span-2 lg:col-span-3' 
                          : 'col-span-1'
                      )}
                    >
                      <Controller
                        name={field.fieldname}
                        control={control}
                        render={({ field: formField, fieldState }) => (
                          <FieldRenderer
                            field={field}
                            value={formField.value}
                            onChange={formField.onChange}
                            error={fieldState.error?.message}
                            disabled={isReadOnly || field.read_only}
                            doctype={doctype}
                            allValues={watch()}
                          />
                        )}
                      />
                    </div>
                  ))}
                </div>
              </Card.Content>
            </Card>
          </motion.div>
        ))}
      </div>
    </form>
  );
};

export default DynamicForm;
